[build]
target = "avr-atmega32u4.json"

[target.'cfg(target_arch = "avr")']
runner = ["dfu-programmer", "atmega32u4"]

[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mangled-names"]
